name: Build on Windows

on:
  pull_request:
    branches: [main]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Get latest CMake
        uses: lukka/get-cmake@latest

      - name: Prepare vcpkg
        uses: lukka/run-vcpkg@v6
        with:
          vcpkgArguments: 'eigen3'
          vcpkgTriplet: x64-windows
          vcpkgDirectory: '${{ runner.workspace }}/b/vcpkg'
          vcpkgGitCommitId: ec6fe06e8da05a8157dc8581fa96b36b571c1bd5

      # Runs a single command using the runners shell
      - name: Run CMake & Ninja
        uses: lukka/run-cmake@v3
        id: runcmake
        with:
          cmakeGenerator: 'Ninja'  
          cmakeListsOrSettingsJson: 'CMakeListsTxtBasic'
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          useVcpkgToolchainFile: true
          buildWithCMakeArgs: '-- -v'
          buildDirectory: '${{ runner.workspace }}/b/ninja/'
      